packages:
  - apps/*
  - packages/*

catalog:
  "@changesets/cli": 2.29.5
  "@commitlint/cli": 19.8.1
  "@commitlint/config-conventional": 19.8.1
  "@commitlint/cz-commitlint": 19.8.1
  "@commitlint/types": 19.8.1
  "@eslint/js": 9.33.0
  "@headlessui/react": 2.2.7
  "@mapbox/rehype-prism": 0.9.0
  "@mdx-js/loader": 3.1.0
  "@mdx-js/react": 3.1.0
  "@next/eslint-plugin-next": 15.4.5
  "@next/mdx": 15.4.5
  "@tailwindcss/postcss": 4.1.11
  "@tailwindcss/typography": 0.5.16
  "@testing-library/jest-dom": 6.6.3
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@types/body-parser": 1.19.6
  "@types/cors": 2.8.19
  "@types/express": 5.0.3
  "@types/mdx": 2.0.13
  "@types/morgan": 1.9.10
  "@types/node": 24.2.0
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  "@types/supertest": 6.0.3
  "@typescript-eslint/eslint-plugin": 8.39.0
  "@typescript-eslint/parser": 8.39.0
  "@typescript-eslint/type-utils": 8.39.0
  "@typescript-eslint/types": 8.39.0
  "@typescript-eslint/utils": 8.39.0
  "@vitejs/plugin-react": 5.0.0
  "@vitest/coverage-v8": 3.2.4
  "@vitest/eslint-plugin": 1.3.4
  "@vitest/ui": 3.2.4
  autoprefixer: 10.4.21
  body-parser: 2.2.0
  cheerio: 1.1.2
  clsx: 2.1.1
  cors: 2.8.5
  czg: 1.11.1
  eslint: 9.33.0
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  eslint-plugin-only-warn: 1.1.0
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-react-refresh: 0.4.20
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-turbo: 2.5.5
  eslint-plugin-unused-imports: 4.1.4
  express: 5.1.0
  fast-glob: 3.3.3
  feed: 5.1.0
  globals: 16.3.0
  husky: 9.1.7
  jsdom: 27.0.0
  lint-staged: 16.0.0
  morgan: 1.10.1
  next: 15.4.6
  next-themes: 0.4.6
  nodemon: 3.1.10
  postcss: 8.5.6
  prettier: 3.6.2
  prettier-plugin-packagejson: 2.5.13
  prettier-plugin-pkg: 0.19.1
  prettier-plugin-tailwindcss: 0.6.11
  rantail: 0.0.6
  react: 19.2.0
  react-dom: 19.2.0
  react-hook-form: 7.58.1
  react-intersection-observer: 9.16.0
  react-router: 7.8.0
  remark-gfm: 4.0.1
  rimraf: 6.0.1
  sharp: 0.34.3
  sort-package-json: 3.4.0
  supertest: 7.1.4
  tailwind-merge: 3.3.1
  tailwindcss: 4.1.11
  tsconfig-paths: 4.2.0
  tsdown: 0.14.1
  tslib: 2.8.1
  tsx: 4.20.3
  turbo: 2.5.5
  typescript: 5.8.3
  typescript-eslint: 8.39.0
  validate-branch-name: 1.3.2
  vite: 7.1.10
  vite-plugin-devtools-json: 0.4.1
  vitest: 3.2.4

catalogMode: strict
