packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@commitlint/cli": 20.4.2
  "@commitlint/config-conventional": 20.4.2
  "@commitlint/types": 20.4.0
  "@elysiajs/cors": 1.4.1
  "@elysiajs/node": 1.4.5
  "@elysiajs/openapi": 1.4.14
  "@eslint/js": 10.0.1
  "@headlessui/react": 2.2.9
  "@heroicons/react": 2.2.0
  "@next/eslint-plugin-next": 16.1.6
  "@playwright/test": 1.58.2
  "@sanity/client": 7.16.0
  "@sanity/image-url": 2.0.3
  "@sanity/prettier-config": 3.0.0
  "@sanity/uuid": 3.0.2
  "@tailwindcss/postcss": 4.2.1
  "@tailwindcss/typography": 0.5.19
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.2
  "@testing-library/user-event": 14.6.1
  "@types/node": 25.3.3
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@typescript-eslint/eslint-plugin": 8.56.1
  "@typescript-eslint/parser": 8.56.1
  "@typescript-eslint/type-utils": 8.56.1
  "@typescript-eslint/utils": 8.56.1
  "@vitejs/plugin-react": 5.1.4
  "@vitest/coverage-v8": 4.0.18
  "@vitest/eslint-plugin": 1.6.9
  "@vitest/ui": 4.0.18
  autoprefixer: 10.4.27
  bunchee: 6.9.4
  cheerio: 1.2.0
  clsx: 2.1.1
  czg: 1.12.0
  elysia: 1.4.26
  eslint: 10.0.1
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  eslint-plugin-jest-dom: 5.5.0
  eslint-plugin-only-warn: 1.2.1
  eslint-plugin-prettier: 5.5.5
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.5.2
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-testing-library: 7.16.0
  eslint-plugin-turbo: 2.8.12
  eslint-plugin-unused-imports: 4.4.1
  fast-glob: 3.3.3
  feed: 5.2.0
  fuse.js: 7.1.0
  globals: 17.3.0
  husky: 9.1.7
  jsdom: 28.1.0
  lint-staged: 16.3.0
  next: 16.1.6
  next-intl: 4.8.3
  next-sanity: 12.1.0
  next-themes: 0.4.6
  nodemon: 3.1.14
  pnpm-catalog-updates: 1.1.8
  postcss: 8.5.6
  postcss-scss: 4.0.9
  prettier: 3.8.1
  prettier-plugin-packagejson: 3.0.0
  prettier-plugin-pkg: 0.21.2
  prettier-plugin-tailwindcss: 0.7.2
  react: 19.2.4
  react-dom: 19.2.4
  react-hook-form: 7.71.2
  react-intersection-observer: 10.0.3
  react-router: 7.13.1
  rimraf: 6.1.3
  sanity: 5.12.0
  sharp: 0.34.5
  styled-components: ^6.3.11
  stylelint: 17.4.0
  stylelint-config-standard: 40.0.0
  tailwind-merge: 3.5.0
  tailwindcss: 4.2.1
  turbo: 2.8.12
  typescript: 5.9.3
  typescript-eslint: 8.56.1
  validate-branch-name: 1.3.2
  vite: 7.3.1
  vite-plugin-devtools-json: 1.0.0
  vitest: 4.0.18
catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver
