packages:
  - apps/*
  - packages/*

catalog:
  '@changesets/cli': 2.29.8
  '@commitlint/cli': 20.2.0
  '@commitlint/config-conventional': 20.2.0
  '@commitlint/cz-commitlint': 20.2.0
  '@commitlint/types': 20.2.0
  '@eslint/js': 9.39.2
  '@headlessui/react': 2.2.9
  '@mdx-js/loader': 3.1.1
  '@mdx-js/react': 3.1.1
  '@next/eslint-plugin-next': 16.1.1
  '@next/mdx': 16.1.1
  '@tailwindcss/postcss': 4.1.18
  '@tailwindcss/typography': 0.5.19
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/react': 16.3.1
  '@testing-library/user-event': 14.6.1
  '@types/body-parser': 1.19.6
  '@types/cors': 2.8.19
  '@types/express': 5.0.6
  '@types/mdx': 2.0.13
  '@types/morgan': 1.9.10
  '@types/node': 25.0.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@types/supertest': 6.0.3
  '@typescript-eslint/eslint-plugin': 8.51.0
  '@typescript-eslint/parser': 8.51.0
  '@typescript-eslint/type-utils': 8.51.0
  '@typescript-eslint/utils': 8.51.0
  '@vitejs/plugin-react': 5.1.2
  '@vitest/coverage-v8': 4.0.16
  '@vitest/eslint-plugin': 1.6.4
  '@vitest/ui': 4.0.16
  autoprefixer: 10.4.23
  body-parser: 2.2.1
  bunchee: 6.9.3
  cheerio: 1.1.2
  clsx: 2.1.1
  cors: 2.8.5
  czg: 1.12.0
  eslint: 9.39.2
  eslint-config-prettier: 10.1.8
  eslint-import-resolver-typescript: 4.4.4
  eslint-plugin-import: 2.32.0
  eslint-plugin-jest-dom: 5.5.0
  eslint-plugin-only-warn: 1.1.0
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.26
  eslint-plugin-simple-import-sort: 12.1.1
  eslint-plugin-testing-library: 7.15.4
  eslint-plugin-turbo: 2.7.2
  eslint-plugin-unused-imports: 4.3.0
  express: 5.2.1
  fast-glob: 3.3.3
  feed: 5.1.0
  globals: 16.5.0
  husky: 9.1.7
  jsdom: 27.4.0
  lint-staged: 16.2.7
  morgan: 1.10.1
  next: 16.1.1
  next-intl: 4.7.0
  next-themes: 0.4.6
  nodemon: 3.1.11
  postcss: 8.5.6
  prettier: 3.7.4
  prettier-plugin-packagejson: 2.5.20
  prettier-plugin-pkg: 0.21.2
  prettier-plugin-tailwindcss: 0.7.2
  rantail: 0.0.6
  react: 19.2.3
  react-dom: 19.2.3
  react-hook-form: 7.69.0
  react-intersection-observer: 10.0.0
  react-router: 7.11.0
  rimraf: 6.1.2
  sharp: 0.34.5
  sort-package-json: 3.6.0
  supertest: 7.1.4
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  turbo: 2.7.2
  typescript: 5.9.3
  typescript-eslint: 8.51.0
  validate-branch-name: 1.3.2
  vite: 7.3.0
  vite-plugin-devtools-json: 1.0.0
  vitest: 4.0.16

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver
