export type StableHtmlElementCategory =
  | "Document metadata"
  | "Sectioning root and content"
  | "Text content"
  | "Inline text semantics"
  | "Image and multimedia"
  | "Embedded content"
  | "Scripting"
  | "Demarcating edits"
  | "Table content"
  | "Forms"
  | "Interactive elements"
  | "Web Components";

export interface StableHtmlElementMetadata {
  readonly tagName: string;
  readonly componentName: string;
  readonly folderName: string;
  readonly category: StableHtmlElementCategory;
  readonly isVoid: boolean;
  readonly defaultProps: Readonly<Record<string, string>>;
  readonly accessibilityNotes: string;
}

export const STABLE_HTML_ELEMENTS = [
  {
    tagName: "html",
    componentName: "Html",
    folderName: "html",
    category: "Document metadata",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "head",
    componentName: "Head",
    folderName: "head",
    category: "Document metadata",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "title",
    componentName: "Title",
    folderName: "title",
    category: "Document metadata",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "base",
    componentName: "Base",
    folderName: "base",
    category: "Document metadata",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "link",
    componentName: "Link",
    folderName: "link",
    category: "Document metadata",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "meta",
    componentName: "Meta",
    folderName: "meta",
    category: "Document metadata",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "style",
    componentName: "Style",
    folderName: "style",
    category: "Document metadata",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "body",
    componentName: "Body",
    folderName: "body",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "address",
    componentName: "Address",
    folderName: "address",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "article",
    componentName: "Article",
    folderName: "article",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "aside",
    componentName: "Aside",
    folderName: "aside",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "footer",
    componentName: "Footer",
    folderName: "footer",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "header",
    componentName: "Header",
    folderName: "header",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "h1",
    componentName: "Heading",
    folderName: "heading",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use heading levels to describe page and section hierarchy.",
  },
  {
    tagName: "h2",
    componentName: "Heading",
    folderName: "heading",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use heading levels to describe page and section hierarchy.",
  },
  {
    tagName: "h3",
    componentName: "Heading",
    folderName: "heading",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use heading levels to describe page and section hierarchy.",
  },
  {
    tagName: "h4",
    componentName: "Heading",
    folderName: "heading",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use heading levels to describe page and section hierarchy.",
  },
  {
    tagName: "h5",
    componentName: "Heading",
    folderName: "heading",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use heading levels to describe page and section hierarchy.",
  },
  {
    tagName: "h6",
    componentName: "Heading",
    folderName: "heading",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use heading levels to describe page and section hierarchy.",
  },
  {
    tagName: "hgroup",
    componentName: "Hgroup",
    folderName: "hgroup",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "main",
    componentName: "Main",
    folderName: "main",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "nav",
    componentName: "Nav",
    folderName: "nav",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "section",
    componentName: "Section",
    folderName: "section",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "search",
    componentName: "Search",
    folderName: "search",
    category: "Sectioning root and content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "blockquote",
    componentName: "Blockquote",
    folderName: "blockquote",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "dd",
    componentName: "Dd",
    folderName: "dd",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "div",
    componentName: "Div",
    folderName: "div",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "dl",
    componentName: "Dl",
    folderName: "dl",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "dt",
    componentName: "Dt",
    folderName: "dt",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "figcaption",
    componentName: "Figcaption",
    folderName: "figcaption",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "figure",
    componentName: "Figure",
    folderName: "figure",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "hr",
    componentName: "Hr",
    folderName: "hr",
    category: "Text content",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "li",
    componentName: "Li",
    folderName: "li",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "menu",
    componentName: "Menu",
    folderName: "menu",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "ol",
    componentName: "Ol",
    folderName: "ol",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "p",
    componentName: "P",
    folderName: "p",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "pre",
    componentName: "Pre",
    folderName: "pre",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "ul",
    componentName: "Ul",
    folderName: "ul",
    category: "Text content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "a",
    componentName: "A",
    folderName: "a",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {
      href: "#",
    },
    accessibilityNotes:
      'Use a meaningful accessible name; target="_blank" is protected with noopener and noreferrer by default.',
  },
  {
    tagName: "abbr",
    componentName: "Abbr",
    folderName: "abbr",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "b",
    componentName: "B",
    folderName: "b",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "bdi",
    componentName: "Bdi",
    folderName: "bdi",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "bdo",
    componentName: "Bdo",
    folderName: "bdo",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "br",
    componentName: "Br",
    folderName: "br",
    category: "Inline text semantics",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "cite",
    componentName: "Cite",
    folderName: "cite",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "code",
    componentName: "Code",
    folderName: "code",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "data",
    componentName: "Data",
    folderName: "data",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "dfn",
    componentName: "Dfn",
    folderName: "dfn",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "em",
    componentName: "Em",
    folderName: "em",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "i",
    componentName: "I",
    folderName: "i",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "kbd",
    componentName: "Kbd",
    folderName: "kbd",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "mark",
    componentName: "Mark",
    folderName: "mark",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "q",
    componentName: "Q",
    folderName: "q",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "rp",
    componentName: "Rp",
    folderName: "rp",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "rt",
    componentName: "Rt",
    folderName: "rt",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "ruby",
    componentName: "Ruby",
    folderName: "ruby",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "s",
    componentName: "S",
    folderName: "s",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "samp",
    componentName: "Samp",
    folderName: "samp",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "small",
    componentName: "Small",
    folderName: "small",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "span",
    componentName: "Span",
    folderName: "span",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "strong",
    componentName: "Strong",
    folderName: "strong",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "sub",
    componentName: "Sub",
    folderName: "sub",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "sup",
    componentName: "Sup",
    folderName: "sup",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "time",
    componentName: "Time",
    folderName: "time",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "u",
    componentName: "U",
    folderName: "u",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "var",
    componentName: "Var",
    folderName: "var",
    category: "Inline text semantics",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "wbr",
    componentName: "Wbr",
    folderName: "wbr",
    category: "Inline text semantics",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "area",
    componentName: "Area",
    folderName: "area",
    category: "Image and multimedia",
    isVoid: true,
    defaultProps: {
      alt: "",
    },
    accessibilityNotes:
      "Requires alternative text when the image map area conveys information.",
  },
  {
    tagName: "audio",
    componentName: "Audio",
    folderName: "audio",
    category: "Image and multimedia",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "Provide captions/transcripts when needed.",
  },
  {
    tagName: "img",
    componentName: "Img",
    folderName: "img",
    category: "Image and multimedia",
    isVoid: true,
    defaultProps: {
      alt: "",
      decoding: "async",
      src: "#",
    },
    accessibilityNotes:
      'Requires useful alt text unless the image is decorative; native images default to decoding="async".',
  },
  {
    tagName: "map",
    componentName: "Map",
    folderName: "map",
    category: "Image and multimedia",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "track",
    componentName: "Track",
    folderName: "track",
    category: "Image and multimedia",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "Use kind, srcLang, and label for timed text tracks.",
  },
  {
    tagName: "video",
    componentName: "Video",
    folderName: "video",
    category: "Image and multimedia",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "Provide captions/transcripts when needed.",
  },
  {
    tagName: "embed",
    componentName: "Embed",
    folderName: "embed",
    category: "Embedded content",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "iframe",
    componentName: "Iframe",
    folderName: "iframe",
    category: "Embedded content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "object",
    componentName: "Object",
    folderName: "object",
    category: "Embedded content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "picture",
    componentName: "Picture",
    folderName: "picture",
    category: "Embedded content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "source",
    componentName: "Source",
    folderName: "source",
    category: "Embedded content",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "svg",
    componentName: "Svg",
    folderName: "svg",
    category: "Embedded content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Provide title/description or aria-hidden depending on whether the graphic is informative.",
  },
  {
    tagName: "math",
    componentName: "Math",
    folderName: "math",
    category: "Embedded content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "Use MathML semantics for mathematical notation.",
  },
  {
    tagName: "canvas",
    componentName: "Canvas",
    folderName: "canvas",
    category: "Scripting",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "noscript",
    componentName: "Noscript",
    folderName: "noscript",
    category: "Scripting",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "script",
    componentName: "Script",
    folderName: "script",
    category: "Scripting",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "del",
    componentName: "Del",
    folderName: "del",
    category: "Demarcating edits",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "ins",
    componentName: "Ins",
    folderName: "ins",
    category: "Demarcating edits",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "caption",
    componentName: "Caption",
    folderName: "caption",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "col",
    componentName: "Col",
    folderName: "col",
    category: "Table content",
    isVoid: true,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "colgroup",
    componentName: "Colgroup",
    folderName: "colgroup",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "table",
    componentName: "Table",
    folderName: "table",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes:
      "Use caption, th scope, and headers/id relationships for complex data tables.",
  },
  {
    tagName: "tbody",
    componentName: "Tbody",
    folderName: "tbody",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "td",
    componentName: "Td",
    folderName: "td",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "tfoot",
    componentName: "Tfoot",
    folderName: "tfoot",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "th",
    componentName: "Th",
    folderName: "th",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "thead",
    componentName: "Thead",
    folderName: "thead",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "tr",
    componentName: "Tr",
    folderName: "tr",
    category: "Table content",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "button",
    componentName: "Button",
    folderName: "button",
    category: "Forms",
    isVoid: false,
    defaultProps: {
      type: "button",
    },
    accessibilityNotes:
      'Defaults to type="button" on native buttons to avoid accidental form submission.',
  },
  {
    tagName: "datalist",
    componentName: "Datalist",
    folderName: "datalist",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "fieldset",
    componentName: "Fieldset",
    folderName: "fieldset",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "form",
    componentName: "Form",
    folderName: "form",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "input",
    componentName: "Input",
    folderName: "input",
    category: "Forms",
    isVoid: true,
    defaultProps: {
      type: "text",
    },
    accessibilityNotes:
      "Pair form controls with labels and descriptions where applicable.",
  },
  {
    tagName: "label",
    componentName: "Label",
    folderName: "label",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "Prefer htmlFor when labeling a separate control.",
  },
  {
    tagName: "legend",
    componentName: "Legend",
    folderName: "legend",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "meter",
    componentName: "Meter",
    folderName: "meter",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "optgroup",
    componentName: "Optgroup",
    folderName: "optgroup",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "option",
    componentName: "Option",
    folderName: "option",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "output",
    componentName: "Output",
    folderName: "output",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "progress",
    componentName: "Progress",
    folderName: "progress",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "select",
    componentName: "Select",
    folderName: "select",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "textarea",
    componentName: "Textarea",
    folderName: "textarea",
    category: "Forms",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "details",
    componentName: "Details",
    folderName: "details",
    category: "Interactive elements",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "dialog",
    componentName: "Dialog",
    folderName: "dialog",
    category: "Interactive elements",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "summary",
    componentName: "Summary",
    folderName: "summary",
    category: "Interactive elements",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "slot",
    componentName: "Slot",
    folderName: "slot",
    category: "Web Components",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
  {
    tagName: "template",
    componentName: "Template",
    folderName: "template",
    category: "Web Components",
    isVoid: false,
    defaultProps: {},
    accessibilityNotes: "",
  },
] as const satisfies readonly StableHtmlElementMetadata[];

export const VOID_HTML_ELEMENTS = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "source",
  "track",
  "wbr",
] as const;

export const EXCLUDED_HTML_ELEMENTS = [
  "acronym",
  "big",
  "center",
  "dir",
  "fencedframe",
  "font",
  "frame",
  "frameset",
  "geolocation",
  "marquee",
  "nobr",
  "noembed",
  "noframes",
  "param",
  "plaintext",
  "rb",
  "rtc",
  "selectedcontent",
  "strike",
  "tt",
  "xmp",
] as const;
