/**
 * @file packages/content-data/src/portfolio.ts
 * @author Guy Romelle Magayano
 * @description Local Portfolio-style content snapshot structured for headless CMS portability.
 */

import type { ContentPortfolioSnapshot } from "@portfolio/api-contracts/content";

/** Portfolio-style local snapshot used to model a Django/Wagtail-ready content graph. */
export const portfolioSnapshot: ContentPortfolioSnapshot = {
  schemaVersion: "1.0",
  profile: {
    id: "profile-guy-romelle",
    name: "Guy Romelle Magayano",
    role: "Software designer, founder, and engineer",
    location: "New York City, NY",
    heroTitle: "Software designer, founder, and amateur astronaut.",
    heroIntro:
      "I build products, write about engineering, and share practical lessons from design systems, platform work, and developer tooling.",
    avatar: {
      id: "image-avatar-guy-romelle",
      src: "https://cdn.example.com/images/avatar-guy-romelle.jpg",
      alt: "Portrait of Guy Romelle Magayano",
      width: 512,
      height: 512,
    },
    status: "published",
  },
  navigation: [
    {
      id: "nav-about",
      label: "About",
      href: "/about",
      order: 1,
      showInHeader: true,
      showInFooter: true,
    },
    {
      id: "nav-articles",
      label: "Articles",
      href: "/articles",
      order: 2,
      showInHeader: true,
      showInFooter: true,
    },
    {
      id: "nav-projects",
      label: "Projects",
      href: "/projects",
      order: 3,
      showInHeader: true,
      showInFooter: true,
    },
    {
      id: "nav-speaking",
      label: "Speaking",
      href: "/speaking",
      order: 4,
      showInHeader: true,
      showInFooter: false,
    },
    {
      id: "nav-uses",
      label: "Uses",
      href: "/uses",
      order: 5,
      showInHeader: true,
      showInFooter: true,
    },
    {
      id: "nav-contact",
      label: "Contact",
      href: "/contact",
      order: 6,
      showInHeader: true,
      showInFooter: true,
    },
  ],
  socialLinks: [
    {
      id: "social-instagram",
      platform: "instagram",
      label: "Follow me on Instagram",
      href: "https://www.instagram.com/guyromellemagayano",
      order: 1,
    },
    {
      id: "social-github",
      platform: "github",
      label: "Follow me on GitHub",
      href: "https://github.com/guyromellemagayano",
      order: 2,
    },
    {
      id: "social-linkedin",
      platform: "linkedin",
      label: "Follow me on LinkedIn",
      href: "https://www.linkedin.com/in/guyromellemagayano",
      order: 3,
    },
    {
      id: "social-email",
      platform: "email",
      label: "Send me an email",
      href: "mailto:aspiredtechie2010@gmail.com",
      order: 4,
    },
  ],
  pages: [
    {
      id: "page-home",
      slug: "",
      title: "Home",
      intro:
        "Recent writing, projects, and snapshots from product and engineering work.",
      template: "home",
      sections: [
        {
          type: "hero",
          profileId: "profile-guy-romelle",
          socialLinkIds: [
            "social-instagram",
            "social-github",
            "social-linkedin",
            "social-email",
          ],
        },
        {
          type: "projects",
          title: "Featured projects",
          intro: "Things I’ve built and maintained over the years.",
          projectSlugs: ["planetaria", "animaginary", "heliostream"],
        },
        {
          type: "speaking",
          title: "Speaking",
          intro:
            "Talks and interviews on product engineering and systems design.",
          appearanceSlugs: [
            "scaling-design-systems-without-losing-velocity",
            "building-reliable-content-platforms",
            "engineering-leadership-office-hours",
          ],
        },
        {
          type: "photoGallery",
          title: "From my camera roll",
          photoIds: ["photo-1", "photo-2", "photo-3", "photo-4", "photo-5"],
        },
      ],
      seoTitle: "Guy Romelle Magayano",
      seoDescription:
        "Software designer, founder, and engineer writing about product and platform systems.",
      seoCanonicalPath: "/",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
    {
      id: "page-about",
      slug: "about",
      title: "About",
      intro: "A quick overview of who I am and what I build.",
      template: "about",
      sections: [
        {
          type: "richText",
          title: "Hi, I’m Guy.",
          body: "I design and ship software systems that stay maintainable as products scale. My work spans design systems, DX tooling, API platforms, and frontend architecture.",
        },
        {
          type: "experience",
          title: "Work",
          intro: "A few roles and teams that shaped my approach.",
          experienceIds: [
            "work-planetaria",
            "work-airbnb",
            "work-facebook",
            "work-starbucks",
          ],
        },
      ],
      seoTitle: "About - Guy Romelle Magayano",
      seoDescription:
        "Background, experience, and guiding principles for how I build products.",
      seoCanonicalPath: "/about",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
    {
      id: "page-articles",
      slug: "articles",
      title: "Articles",
      intro:
        "Long-form writing on engineering, architecture, and team process.",
      template: "articles",
      sections: [
        {
          type: "richText",
          body: "Article list content is sourced from article documents and rendered in reverse chronological order.",
        },
      ],
      seoTitle: "Articles - Guy Romelle Magayano",
      seoDescription:
        "Essays and notes on frontend architecture, backend systems, and product engineering.",
      seoCanonicalPath: "/articles",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
    {
      id: "page-projects",
      slug: "projects",
      title: "Projects",
      intro: "Products, tools, and experiments I’ve shipped.",
      template: "projects",
      sections: [
        {
          type: "projects",
          title: "Projects",
          projectSlugs: [
            "planetaria",
            "animaginary",
            "heliostream",
            "cosmos",
            "openshuttle",
          ],
        },
      ],
      seoTitle: "Projects - Guy Romelle Magayano",
      seoDescription:
        "A catalog of products, libraries, and experiments across design and engineering.",
      seoCanonicalPath: "/projects",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
    {
      id: "page-speaking",
      slug: "speaking",
      title: "Speaking",
      intro: "Talks, podcasts, and workshops.",
      template: "speaking",
      sections: [
        {
          type: "speaking",
          title: "Recent appearances",
          appearanceSlugs: [
            "scaling-design-systems-without-losing-velocity",
            "building-reliable-content-platforms",
            "engineering-leadership-office-hours",
          ],
        },
      ],
      seoTitle: "Speaking - Guy Romelle Magayano",
      seoDescription:
        "Conversations on platform engineering, frontend systems, and leadership.",
      seoCanonicalPath: "/speaking",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
    {
      id: "page-uses",
      slug: "uses",
      title: "Uses",
      intro: "Software, hardware, and workflow tools I rely on.",
      template: "uses",
      sections: [
        {
          type: "uses",
          title: "Uses",
          categorySlugs: [
            "workstation",
            "developer-tooling",
            "productivity",
            "recording",
          ],
        },
      ],
      seoTitle: "Uses - Guy Romelle Magayano",
      seoDescription:
        "Recommended tools, setup details, and daily workflow choices.",
      seoCanonicalPath: "/uses",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
    {
      id: "page-contact",
      slug: "contact",
      title: "Contact",
      intro: "Open to consulting, collaboration, and speaking invitations.",
      template: "contact",
      sections: [
        {
          type: "ctaList",
          title: "Get in touch",
          ctas: [
            {
              label: "Send me an email",
              href: "mailto:aspiredtechie2010@gmail.com",
              target: "_blank",
            },
            {
              label: "Connect on LinkedIn",
              href: "https://www.linkedin.com/in/guyromellemagayano",
              target: "_blank",
            },
          ],
        },
      ],
      seoTitle: "Contact - Guy Romelle Magayano",
      seoDescription:
        "Contact information for consulting, collaborations, and speaking engagements.",
      seoCanonicalPath: "/contact",
      hideFromSitemap: false,
      seoNoIndex: false,
      status: "published",
      publishedAt: "2026-03-13T00:00:00.000Z",
      updatedAt: "2026-03-13T00:00:00.000Z",
    },
  ],
  projects: [
    {
      id: "project-planetaria",
      slug: "planetaria",
      name: "Planetaria",
      summary:
        "Creating technology to empower civilians to explore space on their own terms.",
      description:
        "A platform and product ecosystem focused on approachable space exploration experiences.",
      website: {
        label: "planetaria.tech",
        href: "https://planetaria.tech",
        target: "_blank",
      },
      tags: ["product", "space", "platform"],
      featured: true,
      order: 1,
      status: "published",
    },
    {
      id: "project-animaginary",
      slug: "animaginary",
      name: "Animaginary",
      summary:
        "High-performance web animation library, hand-written in optimized WASM.",
      repository: {
        label: "github.com",
        href: "https://github.com/guyromellemagayano",
        target: "_blank",
      },
      tags: ["animation", "wasm", "frontend"],
      featured: true,
      order: 2,
      status: "published",
    },
    {
      id: "project-heliostream",
      slug: "heliostream",
      name: "HelioStream",
      summary:
        "Real-time video streaming library optimized for low-latency delivery.",
      repository: {
        label: "github.com",
        href: "https://github.com/guyromellemagayano",
        target: "_blank",
      },
      tags: ["video", "streaming", "realtime"],
      featured: true,
      order: 3,
      status: "published",
    },
    {
      id: "project-cosmos",
      slug: "cosmos",
      name: "cosmOS",
      summary: "The operating system that powers Planetaria space shuttles.",
      repository: {
        label: "github.com",
        href: "https://github.com/guyromellemagayano",
        target: "_blank",
      },
      tags: ["os", "embedded", "systems"],
      order: 4,
      status: "published",
    },
    {
      id: "project-openshuttle",
      slug: "openshuttle",
      name: "OpenShuttle",
      summary: "Open schematics for an early rocket design that reached orbit.",
      repository: {
        label: "github.com",
        href: "https://github.com/guyromellemagayano",
        target: "_blank",
      },
      tags: ["hardware", "open-source", "aerospace"],
      order: 5,
      status: "published",
    },
  ],
  speakingAppearances: [
    {
      id: "speaking-design-systems-velocity",
      slug: "scaling-design-systems-without-losing-velocity",
      title: "Scaling Design Systems Without Losing Velocity",
      event: "Frontend Foundry Conference",
      category: "conference",
      date: "2025-11-12T00:00:00.000Z",
      location: "San Francisco, CA",
      summary:
        "Practical strategies for balancing governance and shipping speed across product teams.",
      cta: {
        label: "Watch recording",
        href: "https://www.youtube.com/",
        target: "_blank",
      },
      featured: true,
      order: 1,
      status: "published",
    },
    {
      id: "speaking-content-platforms",
      slug: "building-reliable-content-platforms",
      title: "Building Reliable Content Platforms",
      event: "Platform Engineering Podcast",
      category: "podcast",
      date: "2025-09-04T00:00:00.000Z",
      summary:
        "How to make content pipelines resilient while keeping editorial workflows simple.",
      cta: {
        label: "Listen now",
        href: "https://www.youtube.com/",
        target: "_blank",
      },
      featured: true,
      order: 2,
      status: "published",
    },
    {
      id: "speaking-leadership-office-hours",
      slug: "engineering-leadership-office-hours",
      title: "Engineering Leadership Office Hours",
      event: "Builders Guild",
      category: "panel",
      date: "2025-06-21T00:00:00.000Z",
      summary:
        "A panel session on coaching IC growth, architecture reviews, and delivery confidence.",
      order: 3,
      status: "published",
    },
  ],
  useCategories: [
    {
      id: "use-category-workstation",
      slug: "workstation",
      title: "Workstation",
      intro: "Hardware I use every day.",
      items: [
        {
          id: "use-macbook-pro",
          name: "16-inch MacBook Pro",
          summary: "My primary machine for engineering and design work.",
          order: 1,
        },
        {
          id: "use-studio-display",
          name: "Apple Studio Display",
          summary: "Main display for coding and visual review tasks.",
          order: 2,
        },
      ],
      order: 1,
      status: "published",
    },
    {
      id: "use-category-developer-tooling",
      slug: "developer-tooling",
      title: "Developer tooling",
      intro: "Core tools in my build and delivery workflow.",
      items: [
        {
          id: "use-nextjs",
          name: "Next.js + Turborepo",
          summary: "App framework and monorepo pipeline foundation.",
          order: 1,
        },
        {
          id: "use-playwright",
          name: "Playwright",
          summary: "Primary browser automation and end-to-end test tooling.",
          order: 2,
        },
      ],
      order: 2,
      status: "published",
    },
    {
      id: "use-category-productivity",
      slug: "productivity",
      title: "Productivity",
      intro: "How I organize daily planning and notes.",
      items: [
        {
          id: "use-notion",
          name: "Notion",
          summary: "Roadmaps, planning docs, and weekly review workflows.",
          order: 1,
        },
        {
          id: "use-linear",
          name: "Linear",
          summary: "Issue tracking and product delivery operations.",
          order: 2,
        },
      ],
      order: 3,
      status: "published",
    },
    {
      id: "use-category-recording",
      slug: "recording",
      title: "Recording",
      intro: "Tools for audio/video calls and content creation.",
      items: [
        {
          id: "use-shure-mv7",
          name: "Shure MV7",
          summary: "Mic for calls, workshops, and recordings.",
          order: 1,
        },
        {
          id: "use-obs",
          name: "OBS Studio",
          summary: "Scene composition and recording for demos and talks.",
          order: 2,
        },
      ],
      order: 4,
      status: "published",
    },
  ],
  workExperience: [
    {
      id: "work-planetaria",
      company: "Planetaria",
      role: "CEO",
      startDate: "2019-01-01",
      isCurrentRole: true,
      summary:
        "Leading product strategy, engineering direction, and operations.",
      order: 1,
      status: "published",
    },
    {
      id: "work-airbnb",
      company: "Airbnb",
      role: "Product Designer",
      startDate: "2014-01-01",
      endDate: "2019-01-01",
      summary:
        "Designed user-facing product surfaces and collaborative systems.",
      order: 2,
      status: "published",
    },
    {
      id: "work-facebook",
      company: "Facebook",
      role: "iOS Software Engineer",
      startDate: "2011-01-01",
      endDate: "2014-01-01",
      summary:
        "Built iOS features with a focus on reliability and performance.",
      order: 3,
      status: "published",
    },
    {
      id: "work-starbucks",
      company: "Starbucks",
      role: "Shift Supervisor",
      startDate: "2008-01-01",
      endDate: "2011-01-01",
      summary: "Learned early leadership and operations fundamentals.",
      order: 4,
      status: "published",
    },
  ],
  photos: [
    {
      id: "photo-1",
      image: {
        id: "photo-image-1",
        src: "https://cdn.example.com/photos/image-1.jpg",
        alt: "Desk setup near a window",
        width: 1280,
        height: 1422,
      },
      order: 1,
      status: "published",
    },
    {
      id: "photo-2",
      image: {
        id: "photo-image-2",
        src: "https://cdn.example.com/photos/image-2.jpg",
        alt: "Notebook and keyboard on a wooden desk",
        width: 1280,
        height: 1422,
      },
      order: 2,
      status: "published",
    },
    {
      id: "photo-3",
      image: {
        id: "photo-image-3",
        src: "https://cdn.example.com/photos/image-3.jpg",
        alt: "City lights from a rooftop at dusk",
        width: 1280,
        height: 1422,
      },
      order: 3,
      status: "published",
    },
    {
      id: "photo-4",
      image: {
        id: "photo-image-4",
        src: "https://cdn.example.com/photos/image-4.jpg",
        alt: "Coffee cup beside laptop during writing session",
        width: 1280,
        height: 1422,
      },
      order: 4,
      status: "published",
    },
    {
      id: "photo-5",
      image: {
        id: "photo-image-5",
        src: "https://cdn.example.com/photos/image-5.jpg",
        alt: "Candid travel photo on a city street",
        width: 1280,
        height: 1422,
      },
      order: 5,
      status: "published",
    },
  ],
};
